name: Z3Gateway Control Panel
version: "0.1.6"
slug: z3gateway_control_panel
description: Local web control panel for Silicon Labs zigbee_z3_gateway host.
arch:
  - aarch64
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8765
panel_icon: mdi:zigbee
panel_title: Z3Gateway
uart: true
udev: true
ports:
  8765/tcp: null
ports_description:
  8765/tcp: Optional direct access to the Z3Gateway web console.
options:
  serial_port: /dev/ttyUSB0
  network_index: "1"
  baud_rate: "115200"
schema:
  serial_port: device(subsystem=tty)
  calibration_serial_port: "device(subsystem=tty)?"
  network_index: str
  baud_rate: str
